name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test-and-deploy: # 👈 ต้องมี jobs.<jobid>
    runs-on: ubuntu-latest

    steps: # 👈 แล้วทุก step ต้องอยู่ใต้ steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true

      # -------------------------------
      # Allure Reports
      # -------------------------------
      - name: Upload allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 14

      - name: Debug allure-results
        if: always()
        run: ls -R allure-results || echo "❌ allure-results folder missing"

      - name: Install Allure
        if: always()
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure report
        if: always()
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 14

      # -------------------------------
      # JUnit + Summary
      # -------------------------------
      - name: Publish JUnit Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: "junit-results/*.xml"

      - name: Publish Test Summary Report
        uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: json-results/results.json

      # -------------------------------
      # Netlify Deploy
      # -------------------------------
      - name: Install Netlify CLI
        if: always()
        run: npm install -g netlify-cli

      - name: Check Netlify version
        if: always()
        run: netlify --version

      - name: Deploy Allure report to Netlify (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          netlify deploy \
            --dir=allure-report \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --prod

      - name: Add Netlify Deploy Button
        if: github.ref == 'refs/heads/main'
        uses: actions/github-script@v7
        with:
          script: |
            const url = "https://YOUR-SITE.netlify.app";
            core.summary
              .addHeading("✅ Allure Report Deployed")
              .addLink("👉 Click here to view Allure Report", url)
              .addEOL()
              .write()
