name: Playwright Tests with Allure and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests with Allure
        run: npm run test:report
        continue-on-error: true

      - name: Install Allure Commandline
        run: npm install -g allure-commandline --save-dev

      - name: List allure-results
        if: always()
        run: ls -R ./allure-results || echo "No allure-results found"

      - name: Generate Allure Report
        if: always()
        run: npm run allure:generate

      - name: Upload Allure Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Allure Report Artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      # -------------------------------
      # Netlify Deploy
      # -------------------------------
      - name: Install Netlify CLI
        if: always()
        run: npm install -g netlify-cli

      - name: Check Netlify version
        if: always()
        run: netlify --version

      - name: Deploy Allure report to Netlify (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          netlify deploy \
            --dir=allure-report \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --prod-if-unlocked
      - name: Add Netlify Deploy Button
        if: github.ref == 'refs/heads/main'
        uses: actions/github-script@v7
        with:
          script: |
            const url = "https://YOUR-SITE.netlify.app";
            core.summary
              .addHeading("✅ Allure Report Deployed")
              .addLink("👉 Click here to view Allure Report", url)
              .addEOL()
              .write()
