name: CI

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  test-and-deploy: # 👈 ต้องมี jobs.<jobid>
    runs-on: ubuntu-latest

    steps: # 👈 แล้วทุก step ต้องอยู่ใต้ steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install
        run: npm ci

      - name: Setup Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=list,json=json-results/results.json
        continue-on-error: true

      - name: Debug json-results
        if: always()
        run: ls -R json-results || echo "❌ json-results folder missing"

      # -------------------------------
      # Allure Reports
      # -------------------------------
      - name: Upload allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 14

      - name: Debug allure-results
        if: always()
        run: ls -R allure-results || echo "❌ allure-results folder missing"

      - name: Install Allure
        if: always()
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure report
        if: always()
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 14

      # -------------------------------
      # JUnit + Summary
      # -------------------------------
      - name: Publish JUnit Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: "junit-results/*.xml"

      - name: Publish Test Summary Report
        uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: json-results/results.json

      # -------------------------------
      # Netlify Deploy
      # -------------------------------
      - name: Install Netlify CLI
        if: always()
        run: npm install -g netlify-cli

      - name: Check Netlify version
        if: always()
        run: netlify --version

      - name: Debug GitHub Ref
        run: |
          echo "github.ref      = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event_name = ${{ github.event_name }}"

      - name: Deploy Allure report to Netlify (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          netlify deploy \
            --dir=allure-report \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --prod
